version: '3.7'

services:

    mosquitto:
      image: eclipse-mosquitto
      restart: always
      container_name: mosquitto
      volumes:
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      ports:
        - 1883:1883
      network_mode: "host"
    zigbee2mqtt:
      container_name: zigbee2mqtt
      image: koenkk/zigbee2mqtt:latest-dev
      ports:
        - 8080:8080
      volumes:
        - ./zigbee2mqtt:/app/data
        - /run/udev:/run/udev:ro
      devices:
        - /dev/ttyACM0:/dev/ttyACM0
      restart: always
      network_mode: host
      privileged: true
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      environment:
        - TZ=Europe/Prague
    node-red:
      container_name: node-red
      image: nodered/node-red:latest
      restart: always
      network_mode: host
      environment:
        - TZ=Europe/Prague
      ports:
        - 1880:1880
        - 54545:54545
        - 45454:45454
      volumes:
        - ./nodered:/data

