experimental:
  new_api: true
frontend:
  port: 8080
homeassistant: false
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
serial:
  port: /dev/ttyACM0
advanced:
  network_key: GENERATE
